---
title: "Readme.Rmd"
author: "Liangkang Wang"
date: "6/18/2022"
output: 
  md_document:
    variant: markdown_github
---
## Installation

You can install singR from github with:
```{r,eval=FALSE}
library(devtools)
install_github("GanzhongTian/R.CenGMR")
library(R.CenGMR)
```

Generate Simulation data and their parameters:
```{r}
set.seed(22) 

BETA=list(matrix(c(2,0,20,-2),nrow=2,ncol=2),
          matrix(c(3,1,25,-3),nrow=2,ncol=2),
          matrix(c(3.5,2,30,-5),nrow=2,ncol=2))

SIGMA=list(matrix(c(1,0.1,0.1,1),nrow=2,ncol=2),
           matrix(c(2,0.2,0.2,0.5),nrow=2,ncol=2),
           matrix(c(0.5,0.3,0.3,2),nrow=2,ncol=2))
PIE=c(.1,.7,.2)

message("A vector of Mixing porportions: ")
print(PIE)

message("A list of Beta matrices: ")
print(BETA)

message("A list of Sigma matrices: ")
print(SIGMA)
```

```{r}
example_true_pars=list(PIE,BETA,SIGMA)
names(example_true_pars)=c('PIE','BETA','SIGMA')
#save(example_true_pars,file = "example_true_pars.RData")

example_true=TrueDataGen(1,1000,PIE,BETA,SIGMA)
```

